export interface IndianStockMetadata {
  symbol: string;
  name: string;
  sector: string;
  exchange: "NSE" | "BSE";
}

export const REAL_NSE_STOCKS: IndianStockMetadata[] = [
  // BANKING
  { symbol: "HDFCBANK", name: "HDFC Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "ICICIBANK", name: "ICICI Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking", exchange: "NSE" },
  { symbol: "AXISBANK", name: "Axis Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "BOB", name: "Bank of Baroda", sector: "Banking", exchange: "NSE" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "YESBANK", name: "Yes Bank Limited", sector: "Banking", exchange: "BSE" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "FEDERALBNK", name: "The Federal Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "AUBANK", name: "AU Small Finance Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "IDBI", name: "IDBI Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "UCOBANK", name: "UCO Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "CENTRALBK", name: "Central Bank of India", sector: "Banking", exchange: "NSE" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking", exchange: "NSE" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", sector: "Banking", exchange: "NSE" },
  { symbol: "BANKINDIA", name: "Bank of India", sector: "Banking", exchange: "NSE" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking", exchange: "NSE" },
  { symbol: "J&KBANK", name: "The Jammu & Kashmir Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "SOUTHBANK", name: "The South Indian Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "CUB", name: "City Union Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "EQUITASSFB", name: "Equitas Small Finance Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "CSBBANK", name: "CSB Bank Limited", sector: "Banking", exchange: "NSE" },
  { symbol: "ESFASFB", name: "ESAF Small Finance Bank Limited", sector: "Banking", exchange: "NSE" },

  // IT (INFORMATION TECHNOLOGY)
  { symbol: "TCS", name: "Tata Consultancy Services Limited", sector: "IT", exchange: "NSE" },
  { symbol: "INFY", name: "Infosys Limited", sector: "IT", exchange: "NSE" },
  { symbol: "WIPRO", name: "Wipro Limited", sector: "IT", exchange: "NSE" },
  { symbol: "HCLTECH", name: "HCL Technologies Limited", sector: "IT", exchange: "NSE" },
  { symbol: "TECHM", name: "Tech Mahindra Limited", sector: "IT", exchange: "NSE" },
  { symbol: "LTIM", name: "LTIMindtree Limited", sector: "IT", exchange: "NSE" },
  { symbol: "COFORGE", name: "Coforge Limited", sector: "IT", exchange: "NSE" },
  { symbol: "PERSISTENT", name: "Persistent Systems Limited", sector: "IT", exchange: "NSE" },
  { symbol: "MPHASIS", name: "Mphasis Limited", sector: "IT", exchange: "NSE" },
  { symbol: "KPITTECH", name: "KPIT Technologies Limited", sector: "IT", exchange: "NSE" },
  { symbol: "OFSS", name: "Oracle Financial Services Software Limited", sector: "IT", exchange: "NSE" },
  { symbol: "LTTS", name: "L&T Technology Services Limited", sector: "IT", exchange: "NSE" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Limited", sector: "IT", exchange: "NSE" },
  { symbol: "CYIENT", name: "Cyient Limited", sector: "IT", exchange: "NSE" },
  { symbol: "SONATSOFTW", name: "Sonata Software Limited", sector: "IT", exchange: "NSE" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Limited", sector: "IT", exchange: "NSE" },
  { symbol: "BSOFT", name: "BirlaSoft Limited", sector: "IT", exchange: "NSE" },
  { symbol: "INTELLECT", name: "Intellect Design Arena Limited", sector: "IT", exchange: "NSE" },
  { symbol: "MASTEK", name: "Mastek Limited", sector: "IT", exchange: "NSE" },
  { symbol: "AFFLE", name: "Affle (India) Limited", sector: "IT", exchange: "NSE" },
  { symbol: "TANLA", name: "Tanla Platforms Limited", sector: "IT", exchange: "NSE" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies Limited", sector: "IT", exchange: "NSE" },
  { symbol: "CEINFO", name: "MapmyIndia (C.E. Info Systems)", sector: "IT", exchange: "NSE" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies Limited", sector: "IT", exchange: "NSE" },

  // AUTOMOBILE & AUTO COMPONENTS
  { symbol: "TATAMOTORS", name: "Tata Motors Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "M&M", name: "Mahindra & Mahindra Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "EICHERMOT", name: "Eicher Motors Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "MRF", name: "MRF Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "CEATLTD", name: "CEAT Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "EXIDEIND", name: "Exide Industries Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "BOSCHLTD", name: "Bosch Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "BHARATFORG", name: "Bharat Forge Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "TUBEINVEST", name: "Tube Investments of India Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "ESCORTS", name: "Escorts Kubota Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "SUPRAJIT", name: "Suprajit Engineering Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation Limited", sector: "Automobile", exchange: "NSE" },
  { symbol: "ROLEXRINGS", name: "Rolex Rings Limited", sector: "Automobile", exchange: "NSE" },

  // PHARMACEUTICALS & HEALTHCARE
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "CIPLA", name: "Cipla Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "APLLHOSP", name: "Apollo Hospitals Enterprise Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "LUPIN", name: "Lupin Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "ALKEM", name: "Alkem Laboratories Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "BIOCON", name: "Biocon Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "GLAND", name: "Gland Pharma Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "SYNGENE", name: "Syngene International Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "FORTIS", name: "Fortis Healthcare Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "GRANULES", name: "Granules India Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "JBCHEPHARM", name: "J.B. Chemicals & Pharmaceuticals Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "ABBOTINDIA", name: "Abbott India Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "SANOFI", name: "Sanofi India Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "ERIS", name: "Eris Lifesciences Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "NATCOPHARM", name: "Natco Pharma Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare Limited", sector: "Pharma", exchange: "NSE" },
  { symbol: "NARAYANA", name: "Narayana Hrudayalaya Limited", sector: "Pharma", exchange: "NSE" },

  // ENERGY, OIL & GAS & POWER
  { symbol: "RELIANCE", name: "Reliance Industries Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "NTPC", name: "NTPC Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "COALINDIA", name: "Coal India Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "IOC", name: "Indian Oil Corporation Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "HPCL", name: "Hindustan Petroleum Corporation Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "TATAPOWER", name: "Tata Power Company Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "JSWENERGY", name: "JSW Energy Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "SJVN", name: "SJVN Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "NHPC", name: "NHPC Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "ADANIPOWER", name: "Adani Power Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "GAIL", name: "GAIL (India) Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "PETRONET", name: "Petronet LNG Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "IGL", name: "Indraprastha Gas Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "MGL", name: "Mahanagar Gas Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "OIL", name: "Oil India Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "TORNTPOWER", name: "Torrent Power Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "CESC", name: "CESC Limited", sector: "Energy", exchange: "NSE" },
  { symbol: "IREDA", name: "Indian Renewable Energy Development Agency Ltd", sector: "Energy", exchange: "NSE" },

  // FMCG (FAST MOVING CONSUMER GOODS)
  { symbol: "ITC", name: "ITC Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "NESTLEIND", name: "Nestle India Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "BRITANNIA", name: "Britannia Industries Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "VBL", name: "Varun Beverages Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "DABUR", name: "Dabur India Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India) Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "MARICO", name: "Marico Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "SHREERENUK", name: "Shree Renuka Sugars Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "DALMIASUG", name: "Dalmia Bharat Sugar and Industries Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "KRBL", name: "KRBL Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "LTFOODS", name: "LT Foods Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "HERITGFOOD", name: "Heritage Foods Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "HATSUN", name: "Hatsun Agro Product Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "TASTYBIT", name: "Tasty Bite Eatables Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "ZYDUSWELL", name: "Zydus Wellness Limited", sector: "FMCG", exchange: "NSE" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Consumer Healthcare Limited", sector: "FMCG", exchange: "NSE" },

  // INFRASTRUCTURE, MATERIALS & CONSTRUCTION
  { symbol: "L&T", name: "Larsen & Toubro Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "ADANIENT", name: "Adani Enterprises Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "ADANIPORTS", name: "Adani Ports and Special Economic Zone Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "IRB", name: "IRB Infrastructure Developers Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "SHREECEM", name: "Shree Cement Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "ACC", name: "ACC Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "GRASIM", name: "Grasim Industries Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "NCC", name: "NCC Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "DLF", name: "DLF Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "GODREJPROP", name: "Godrej Properties Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "SOBHA", name: "Sobha Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "LODHA", name: "Macrotech Developers Limited (Lodha)", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "KNRCON", name: "KNR Constructions Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "PNCINFRA", name: "PNC Infratech Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "DILIPBUILD", name: "Dilip Buildcon Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "JKCEMENT", name: "JK Cement Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "HEIDELBERG", name: "HeidelbergCement India Limited", sector: "Infrastructure", exchange: "NSE" },
  { symbol: "NUVOCI", name: "Nuvoco Vistas Corporation Limited", sector: "Infrastructure", exchange: "NSE" },

  // METALS & MINING
  { symbol: "TATASTEEL", name: "Tata Steel Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "JSWSTEEL", name: "JSW Steel Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "HINDALCO", name: "Hindalco Industries Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "VEDL", name: "Vedanta Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "SAIL", name: "Steel Authority of India Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "NMDC", name: "NMDC Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "NATIONALUM", name: "National Aluminium Company Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "MOIL", name: "MOIL Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "JSL", name: "Jindal Stainless Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "WELCORP", name: "Welspun Corp Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "JINDALSAW", name: "Jindal Saw Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes Limited", sector: "Metals", exchange: "NSE" },
  { symbol: "MAHSEAMLES", name: "Maharashtra Seamless Limited", sector: "Metals", exchange: "NSE" },

  // TELECOM & MEDIA
  { symbol: "BHARTIARTL", name: "Bharti Airtel Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "IDEA", name: "Vodafone Idea Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "TTML", name: "Tata Teleservices (Maharashtra) Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "TEJASNET", name: "Tejas Networks Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "INDUSTOWER", name: "Indus Towers Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "ROUTE", name: "Route Mobile Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "HFCL", name: "HFCL Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "SUNTV", name: "Sun TV Network Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "PVRINOX", name: "PVR INOX Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "DISHTV", name: "Dish TV India Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "HATHWAY", name: "Hathway Cable & Datacom Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "NETWORK18", name: "Network18 Media & Investments Limited", sector: "Telecom", exchange: "NSE" },
  { symbol: "TV18BRDCST", name: "TV18 Broadcast Limited", sector: "Telecom", exchange: "NSE" },

  // FINANCE, INSURANCE & MARKET INTERMEDIARIES
  { symbol: "BAJFINANCE", name: "Bajaj Finance Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "LIC", name: "Life Insurance Corporation of India", sector: "Finance", exchange: "NSE" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism Corporation Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "HAL", name: "Hindustan Aeronautics Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "BEL", name: "Bharat Electronics Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "ZOMATO", name: "Zomato Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "PAYTM", name: "One97 Communications Limited (Paytm)", sector: "Finance", exchange: "NSE" },
  { symbol: "SUZLON", name: "Suzlon Energy Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "TRENT", name: "Trent Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment and Finance Company", sector: "Finance", exchange: "NSE" },
  { symbol: "RECLTD", name: "REC Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "PFC", name: "Power Finance Corporation Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance Company", sector: "Finance", exchange: "NSE" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance Company", sector: "Finance", exchange: "NSE" },
  { symbol: "IEX", name: "Indian Energy Exchange Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "MCX", name: "Multi Commodity Exchange of India Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "CDSL", name: "Central Depository Services (India) Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "BSE", name: "BSE Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Limited (Nykaa)", sector: "Finance", exchange: "NSE" },
  { symbol: "POLICYBZR", name: "PB Fintech Limited (Policybazaar)", sector: "Finance", exchange: "NSE" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corporation Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "IBULHSGFIN", name: "Indiabulls Housing Finance Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "ANGELONE", name: "Angel One Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "5PAISA", name: "5paisa Capital Limited", sector: "Finance", exchange: "NSE" },
  { symbol: "GEPIL", name: "GE Power India Limited", sector: "Finance", exchange: "NSE" },

  // CHEMICALS, FERTILIZERS & AGROCHEMICALS
  { symbol: "SRF", name: "SRF Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "TATACHEM", name: "Tata Chemicals Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "COROMANDEL", name: "Coromandel International Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers and Chemicals Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers & Chemicals Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers & Chemicals", sector: "Chemicals", exchange: "NSE" },
  { symbol: "RCF", name: "Rashtriya Chemicals and Fertilizers Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "FACT", name: "Fertilisers And Chemicals Travancore Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "UPL", name: "UPL Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "PIIND", name: "PI Industries Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "BAYERCROP", name: "Bayer CropScience Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "ATUL", name: "Atul Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "AARTIIND", name: "Aarti Industries Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "VINATIORGA", name: "Vinati Organics Limited", sector: "Chemicals", exchange: "NSE" },
  { symbol: "LAXMICHEM", name: "Laxmi Organic Industries Limited", sector: "Chemicals", exchange: "NSE" },

  // TEXTILES, APPAREL & LUXURY
  { symbol: "PAGEIND", name: "Page Industries Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "KPRMILL", name: "K.P.R. Mill Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "TRIDENT", name: "Trident Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "WELSPUNIND", name: "Welspun Living Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "ALOKTEXT", name: "Alok Industries Limited", sector: "Textiles", exchange: "BSE" },
  { symbol: "RAYMOND", name: "Raymond Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "ARVIND", name: "Arvind Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "GARFIBRES", name: "Garware Technical Fibres Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "LUXIND", name: "Lux Industries Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "SANGAMIND", name: "Sangam (India) Limited", sector: "Textiles", exchange: "NSE" },
  { symbol: "NITINSPIN", name: "Nitin Spinners Limited", sector: "Textiles", exchange: "NSE" },

  // HOTELS, HOSPITALITY & TOURISM
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Limited (Taj)", sector: "Hospitality", exchange: "NSE" },
  { symbol: "EIHOTEL", name: "EIH Limited (Oberoi)", sector: "Hospitality", exchange: "NSE" },
  { symbol: "TAJGVK", name: "TAJGVK Hotels & Resorts Limited", sector: "Hospitality", exchange: "NSE" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Limited", sector: "Hospitality", exchange: "NSE" },
  { symbol: "WONDERLA", name: "Wonderla Holidays Limited", sector: "Hospitality", exchange: "NSE" },
  { symbol: "THOMASCOOK", name: "Thomas Cook (India) Limited", sector: "Hospitality", exchange: "NSE" }
];
